### ISSUE TITLE
Add Colemak layout support 

### ISSUE THREAD

**Issue by delinx** [tris203/hawtkeys.nvim#69]
Hello, I love Colemak and would love to contribute to the layouts, there are few common variants of Colemak. #45

**Comment by tris203** [comment]
Hey @delinx 

all you would need to do, it replicate this format for the new layout

https://github.com/tris203/hawtkeys.nvim/blob/main/lua/hawtkeys/keyboards/qwerty.lua

everything is 1 indexed because lua.
Fingers are indexed from left pink to right pinky

https://github.com/tris203/hawtkeys.nvim/blob/main/lua/hawtkeys/keyboards.lua

then once your layout is in, add a line here.

If there are multiple variants, then we would need a few different files, but I think we are going to have to do that with qwerty for US/UK variants, as I would like to expand to numbers and symbols in the layouts too

**Comment by willothy** [comment]
Is there some sort of universal layout format that's used somewhere? Hopefully something not as complicated as zmk/qmk configs at least? If so we could maybe try auto-generating layouts with a script. Would be much easier than manually maintaining each one and we could keep them up to date with CI.

**Comment by tris203** [comment]
I have looked for a repo of keyboard layouts in some sort of JSON/YAML/XML format, but haven't found anything yet
